# Generated by Django 5.1.3 on 2024-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(help_text='Введите текст здесь', max_length=255),
        ),
    ]
